
name: Hello NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: 'xiaomi_mi-router-3g.config'
      source:
        description: 'Git Source'
        required: true
        default: '1'

jobs:
  build:
    name: ${{ github.event.inputs.config }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y update 2>&1 >/dev/null
        sudo -E apt-get -y install $(cat ./.github/workflows/BuildEnviroment) 2>&1 >/dev/null
        sudo -E apt-get -y autoremove --purge 2>&1 >/dev/null
        sudo -E apt-get -y clean 2>&1 >/dev/null

    - name: Build
      run: |
        chmod +x $GITHUB_WORKSPACE/sh/*.sh
        releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/config/releasetag.list)
        git clone $releasetag nuexini
        cd nuexini
        sh $GITHUB_WORKSPACE/sh/Hello_NueXini.sh
        ./scripts/feeds update -a > /dev/null
        ./scripts/feeds install -a
        cp -rf $GITHUB_WORKSPACE/config/${{ github.event.inputs.config }} ./.config
        sh $GITHUB_WORKSPACE/sh/Hi_NueXini.sh
        make defconfig
        make download -j8
        rm -rf $(find ./dl/ -size -1024c)
        make -j8 || make -j1 V=sc > ./make-error.log 2>&1

    - name: Upload error log
      uses: actions/upload-artifact@master
      if: failure()
      with:
        name: build-failure-log
        path: nuexini/make-error.log
    
    - name: Upload Firmware
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config }}-Firmware
        path: nuexini/bin/targets

    - name: Upload Packages
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config }}-Packages
        path: nuexini/bin/packages
