
name: Hi NueXini

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration File'
        required: true
        default: 'xiaomi_mi-router-3g.config'
      source:
        description: 'Git Source'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build
      run: |
        chmod +x ./sh/*.sh
        releasetag=$(sed -n "${{ github.event.inputs.source }}p" $GITHUB_WORKSPACE/config/releasetag.list)
        git clone $releasetag dd
        cd dd
        mkdir -p ./nuexini
        ../sh/Hello_NueXini.sh
        ./scripts/feeds update -a > /dev/null
        ./scripts/feeds install -a > /dev/null
        cp -rf ../config/${{ github.event.inputs.config }} ./.config
        ln -s ../scripts/makemenuconfig.sh ./dd2.sh
        ../sh/Hi_NueXini.sh
        echo "grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > NX_DEVICE_NAME" > dd.sh
        echo 'cp -rf ./.config ./nuexini/$(cat NX_DEVICE_NAME).config' >> dd.sh
        
    - name: Hi NueXini
      uses: klever1988/ssh2actions@main
      
    - name: Preparation
      run: |
        cd dd
        sh dd.sh

    - name: Last thing
      uses: actions/upload-artifact@master
      with:
        name: config
        path: dd/nuexini

###### ###### ###### ###### ###### 
#    - name: Hi NueXini
#      uses: rdp-studio/ssh2actions@v2.0.0
#      with:
#        mode: ngrok
#      env:
#        SSH_PASSWORD: 'nuexini'
#        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
